### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [sudara/alonetone#207]
First of all, thanks for alonetone!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/alonetone/pulls). I'll port the `paperclip` one across to this repo now.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having open source repos using Dependabot helps boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by sudara** [comment]
Howdy! 

We are using dependabot on a client project and it's quite useful there since they need help updating their deps! Alonetone does a pretty good job of updating deps somewhat regularly since it's a smaller project that I feel "safe" doing a bundle update on, but it might be fun to use here and would be nice to help out.

My only concern might be that PRs not being merged quickly become "noise" — for example on #208, I have about 25 priorities before it's time to look at paperclip again (a deprecated gem) — but it looks like you have nice tooling with `@dependabot ignore`, so maybe it'll be easy to manage?

**Comment by greysteil** [comment]
Hey!

Yeah, `@dependabot ignore` feels like the way to go on paperclip - sorry for picking such a bad example!

Awesome to hear you're using Dependabot elsewhere! You'd totally be helping me out by running it on this repo - the CI runs help improve the quality of its compatibility scores, and since we now link to CI runs that failed it's super valuable to Dependabot to have well tested projects like alonetone using it. Plan is to start feeding back failures to maintainers, with links to the PRs that are failing, so that they can fix bugs in their libraries.

**Comment by sudara** [comment]
Sounds great. Not sure I'd call alonetone too well tested, but I'm more than happy to help.

 I think I actually installed it on alonetone before. I love the auto-merge thing.

Two last questions for you:

1. If i manually bump and push, do the PRs know to close themselves, or will I then have to manually close?

2. Can I run it on my package.json as well as my Gemfile? I actually struggle more with knowing and updating my js dependencies, in part because the tooling/philosophy isn't as nice as bundler (`bundle update` is a pretty nice shotgun blast to get everything up to date)

**Comment by greysteil** [comment]
Yes and yes! The PRs will figure out that they need to close themselves (it takes them a minute), and you can use Dependabot for JS, too - it'll handle updating the `yarn.lock` here just fine 🙂

**Comment by sudara** [comment]
@greysteil Awesome! Sounds like a great workflow. I've got it running but looks like it's only looking at Gemfile right now — is there a config option to have it handle the yarn lock too?

**Comment by sudara** [comment]
Nevermind, got it — "add project" did the trick!

**Comment by greysteil** [comment]
Woah, that's a lot of initial PRs. If you want a hand with any of them just tag me.

**Comment by sudara** [comment]
Thanks! I guess I was wondering how to "bulk" rebase since I got master green again, so I triggered "bump now" on the website..

**Comment by greysteil** [comment]
Ah, OK, that explains why there are so many! 🤦‍♂️ 

They'll automatically rebase if/when they detect that there are any conflicts, so if you merge some of the recent batch the old ones will probably start rebasing.

**Comment by sudara** [comment]
Only other mild "spammy" thing is that the github notifications on bump/CI/merge are quite intense in slack! But I think it'll just be this initial wave and it'll then be pleasant and useful!

**Comment by sudara** [comment]
Yeah, I figured they might rebase at some point, but I got impatient :D

**Comment by sudara** [comment]
@greysteil Loving dependabot on alonetone. It's turned updating deps into a nice game. I really appreciate the easily accessible changelog and link to the diff. It's all very well thought through and saves me time while making me feel a bit more informed about dependency bumping. 

Only minor annoyance is that it's responsible for 75% of the noise in our #commits room 😆

**Comment by greysteil** [comment]
Haha, that’s great to hear! 😀

**Comment by sudara** [comment]
@greysteil Hey, had a quick question for you. I'm quite happy with dependabot but  between js and ruby deps, merging dependabot PRs has turned into a daily whack-a-mole of dependency inbox 0 :)

It's quite noisy in our #commits channel (I can't seem to filter them out via github's slack integration, which is maybe the root problem) — Do you know if others have solved the notification issue at all? I'm sorta loathe to move to a weekly frequency, but if I can't filter notifications I might do that for a while so we get a bit more breathing room...
