### ISSUE TITLE
User listen stats are wrong

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#273]
<img width="415" alt="screenshot" src="https://user-images.githubusercontent.com/472/47970553-608f2200-e087-11e8-9c71-003281be1681.png">

**Comment by innatewonderer** [comment]
@sudara is this still an issue?
I've checked your page and it seems to be showing correct-ish number of `Listens: 39174`

I've checked locally for `number per day` and it shows it correctly but I'm assuming it's because I'm not caching anything locally. Would you please check your account if you are still seeing this issue?

**Comment by sudara** [comment]
@innatewonderer 

I think maybe it's just the per-day value that's wrong?

<img width="323" alt="image" src="https://user-images.githubusercontent.com/472/65925255-4ae9c000-e3f0-11e9-8f7b-b0c81597a2d2.png">

We should just remove that number anyway, it's sorta meaningless to have a daily average. We'll get a chart in here soon which will be more useful.
