### ISSUE TITLE
Comments on home when logged in / moderator differ from guest

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#460]
Please look at the different between the home and https://alonetone.com/comments when logged out.

**Comment by sudara** [comment]
Query on home:

```sql
irb(main):004:0> Comment.to_other_members.last_5_public
  Comment Load (6.5ms)  SELECT `comments`.* FROM `comments` INNER JOIN `users` ON `users`.`deleted_at` IS NULL AND `users`.`id` = `comments`.`commenter_id` WHERE `comments`.`deleted_at` IS NULL AND (users.current_login_ip != remote_ip) AND (commenter_id != user_id) AND `comments`.`commentable_type` = 'Asset' AND `comments`.`is_spam` = FALSE AND `comments`.`private` = FALSE ORDER BY id DESC LIMIT 5
```

on /comments

```sql
irb(main):004:0> Comment.on_track.public_or_private(false).to_sql
=> "SELECT `comments`.* FROM `comments` WHERE `comments`.`deleted_at` IS NULL AND `comments`.`commentable_type` = 'Asset' AND `comments`.`is_spam` = FALSE AND `comments`.`private` = FALSE ORDER BY id DESC"
```

**Comment by sudara** [comment]
Related to https://github.com/sudara/alonetone/pull/391 ?

**Comment by innatewonderer** [comment]
Partially. 
1. Any guest user leaving a comment will be ignored from the query because guest commenter id is nil. I think it's an OK behavior because anyone can still "abuse" the system once they start posting a Guest on their tracks to bring the song up on the front page... but we could exclude guests from that query. 
2. Also, we do not filter `/comments` by comments on my own stuff. I think it's also an OK behavior.

@sudara thoughts?

**Comment by sudara** [comment]
I'm +1 for guest comments and +1 for `/comments` showing everything.

But there's another problem. When I look at https://alonetone.com/comments I'm seeing comments that should be on the homepage — maybe we should get some fixtures in for this? Basically the comments from newbold, the comment on montgomeru's track and the comments from sister savage should all be on the home page in front of what's there now.
