### ISSUE TITLE
Fix css overflow on admin/navigation

### ISSUE THREAD

**Issue by innatewonderer** [sudara/alonetone#579]
When on `http://localhost:3000/admin/users?deleted=true` the active link css of `Deleted` seem to bleed over to `Users` navigation css space.
<img width="1440" alt="Fullscreen_5_4_19__9_27_PM" src="https://user-images.githubusercontent.com/2320322/57186837-05ae7a00-6eb4-11e9-950b-fe67f5a5a0d0.png">

**Comment by ofsound** [comment]
http://localhost:3000/admin/users?deleted=true
http://localhost:3000/admin/users

I believe this is happening because these two links are seen as being the same page by the navigation_item function used in admin/navigation

Instead of /users being inserted into the template as an <a> link, it's being insert as a div with the class .current instead, so you can't click on it, if you are in users?deleted=true

**Comment by sudara** [comment]
Yeah, this is a problem with routes / filter_by. We basically need to make sure the URL is different for "all users" and "only deleted" and then it'll be happy. It's the built in rails helper `link_to_if_current` which is complaining.
