### ISSUE TITLE
Playlist permalinks: Two playlists can have same permalink, making editing impossible

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#660]

**Comment by sudara** [comment]
Good call. Is this only via uploading a zip? Or can you reproduce with manual playlist creation?

**Comment by ofsound** [comment]
I just tried it by manually creating a "Test Playlist" twice, and they appear separate but overlap in editing.

**Comment by sudara** [comment]
#793 describes the desired permalink behavior.

Because permalink/uniqueness implementation differs on assets vs. playlists — playlists are  suffering uniquely — there might be mulitple playlists with the same permalink.

Therefore in addition to relying on new permalink behavior in #793 we require a migration that looks for playlists with the same user and same permalink and creates new permalinks for them.

**Comment by Manfred** [comment]
We might want to add a unique constraint on `user_id` + `permalink` on `playlists` and `assets`,  and on `permalink` for `groups`. For bonus points we can catch `ActiveRecord::RecordNotUnique` in the controllers and render the form when a race condition triggers the problem.

**Comment by Manfred** [comment]
Did we solve this with the migration this week?

**Comment by sudara** [comment]
Yes!
