### ISSUE TITLE
Was able to successfully choose an empty password via Password Reset, but then unable to login again with this empty password

### ISSUE THREAD

**Issue by ofsound** [sudara/alonetone#772]

**Comment by sudara** [comment]
This is still actively a problem on master.

**Comment by sudara** [comment]
This is the same problem and was a result of upgrading to Authlogic 5
https://stackoverflow.com/questions/2174082/force-validation-of-blank-passwords-in-authlogic

Basically, by default, validation of passwords don't occur updating the user model and they are empty, because we want to update other user's fields in a big long form, etc. So Authlogic sees blank passwords and ignores them.

However, when resetting passwords, we do not want to allow blank passwords, as the person is supposed to choose passwords. 

Therefore we actually need to tell Authlogic not to ignore the passwords.

See: https://github.com/binarylogic/authlogic/issues/693
