### ISSUE TITLE
Verify Fastly configuration version 17 and apply

### ISSUE THREAD

**Issue by Manfred** [sudara/alonetone#777]
@sudara Can you verify that I didn't make a mistake and then apply? After the configuration update you should be able to load the following URL successfully:

```
https://fastly.alonetone.com/process/pics/84545/A211703D-531D-49A4-AD6A-BDCDCF7446B0_greenfield.jpeg?crop=1:1&width=250&quality=68
```

**Comment by sudara** [comment]
Version 17 is active but that URL fails.

**Comment by Manfred** [comment]
It seems to work now.

**Comment by sudara** [comment]
> It seems to work now.

Famous last words....

I contacted fastly support and they recommended changing priorities of the rewrite condition, but that didn't help.

I published version 20 and set the priority of the rewrite at "3" so the statement was placed after IO, but it seems we have the same result. 

That didn't work. So I also tried putting the priority of the "linode" backend below the s3 backend, setting it to 10 in version 21.

That didn't work. So I changed the condition so that instead of looking for a url starting with "process" and then rewriting to remove "process", the condition looks for "not starting with what the other host starts with": https://manage.fastly.com/configure/services/11OMGawCB48cOnyQLzRWA1/diff/21,22

That seems happy: 

https://fastly.alonetone.com/process/pics/78926/Wurlibird_3000_greenfield.jpg?width=400
