### ISSUE TITLE
/forums UI issues

### ISSUE THREAD

**Issue by innatewonderer** [sudara/alonetone#963]
<img width="1079" alt="alonetone___Test_board_two" src="https://user-images.githubusercontent.com/2320322/71115461-f14b9300-219f-11ea-83a4-2843da2d637e.png">

- [ ] default image seem to be displayed as a URL rather than some placeholder.
- [ ] new forum thread displays two Start New Thread buttons

**Comment by sudara** [comment]
> default image seem to be displayed as a URL rather than some placeholder.

This is a bit esoteric If you aren't using the seeds (`rake db:reset`) — the seeds will setup 4 boards that are named with a convention which will then then display images there (based on the slug of the board). 

I'm open minded to changing this arrangement, but essentially we are tied to production behavior there, as we don't have much control over thredded (can't do things like store image per board easily).

> new forum thread displays two Start New Thread buttons

What we could do is say "if there are less than 5 threads, don't show the bottom button" — however, the default is to always show a button above and below the list, so this isn't really a production concern. We might be better off fleshing out the database seeds so that there's more in the list.
